format_version: 10
pipelines:
  prometheus:
    group: tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/practice-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main

    stages:
      tools:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            prometheus:
              timeout: 0
              tasks:
                - exec: { command: terraform, arguments: ["init", run_if: passed }
                - exec: { command: terraform, arguments: ["apply", run_if: passed }


