- name: Add vault repo
  ansible.builtin.shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

